# Generated by Django 3.1.2 on 2020-11-09 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebAid', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='opportunity',
            options={'verbose_name_plural': 'Opportunities'},
        ),
        migrations.RemoveField(
            model_name='opportunity',
            name='duration',
        ),
    ]
