# Generated by Django 3.1.2 on 2020-11-11 11:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WebAid', '0004_auto_20201110_1223'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='categories',
            new_name='skills',
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='resolved',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='resolved', to=settings.AUTH_USER_MODEL),
        ),
    ]
