# Generated by Django 3.1.2 on 2020-11-12 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebAid', '0006_auto_20201111_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='subject',
            field=models.CharField(default='Cute puppies', max_length=64),
            preserve_default=False,
        ),
    ]
