# Generated by Django 3.1.2 on 2020-11-18 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WebAid', '0010_auto_20201118_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='resolved',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='opportunity', to='WebAid.resolve'),
        ),
        migrations.AlterField(
            model_name='resolve',
            name='summary',
            field=models.TextField(default='default summary', max_length=1000),
            preserve_default=False,
        ),
    ]
